### ISSUE TITLE
[FR] Possibility of outputting .ics file or linking with Calendar

### ISSUE THREAD

**Issue by hawexrutile** [sdgniser/timetable#18]
### Feature Request / Suggestion

Is it possible to output a .ics file or incorporate it with google calendar?

### Current Behaviour

As of today, the website outputs a pdf file.

### Possible Implementation

It can provide a .ics file (as a downloadable) or mail it to the user(for easier implementation)
A merge of the academic calendar with google calendar would be great.
### Self-check
- [x] I have checked [timetable/issues](https://github.com/sdgniser/timetable/issues) and could not find any related open feature request.

**Comment by PeithonKing** [comment]
Added this feature in [this](https://github.com/sdgniser/timetable/commit/6687eeba6401280a99e5dba46cdf411dfc43d87b) commit. Hence closing it.
