### ISSUE TITLE
[FR] Add data for Spring Semester 2022

### ISSUE THREAD

**Issue by JeS24** [sdgniser/timetable#5]
### Feature Request / Suggestion

Title.

### Current Behaviour

Website has data for last semester.

### Possible Implementation

Add data for new semester from the published timetable.

### Other details

None.

### Self-check
- [x] I have checked [timetable/issues](https://github.com/sdgniser/timetable/issues) and could not find any related open feature request.

**Comment by Abhishek-Deshmukh** [comment]
Updated
