### ISSUE TITLE
[BUG] Missing Legends list in pdf

### ISSUE THREAD

**Issue by Shubhang-sharma** [sdgniser/timetable#8]
### Problem Description
Legends are not printed in the pdf, although the heading is present.

### Expected Behavior
Legends to be listed

**Comment by JeS24** [comment]
What are your courses?

**Comment by Shubhang-sharma** [comment]
Im not sure if the legend shown are supposed to be present in the pdf. 
<img width="419" alt="image" src="https://user-images.githubusercontent.com/68705596/148696867-b2166b26-85c9-454f-afc2-8a2c5924dfbb.png">
<img width="839" alt="image" src="https://user-images.githubusercontent.com/68705596/148696905-0862e235-d6c5-4b40-845f-b1d59d164a4b.png">

**Comment by JeS24** [comment]
They are. Let me try.

**Comment by JeS24** [comment]
Hmm. So they are working fine-ish here:
![image](https://user-images.githubusercontent.com/31299799/148696981-27f85602-5244-44d5-a517-245e5006bda5.png)
![image](https://user-images.githubusercontent.com/31299799/148696983-17590533-1334-4c11-94d4-dab66bc892ad.png)

What is your display resolution and scaling? Also, when you are on the timetable webpage, open browser console (F12 in Chromium/Firefox) and see if there are any errors.

**Comment by Shubhang-sharma** [comment]
150%(set to Recommended one)
1920x1080
and Nope no errors
![image](https://user-images.githubusercontent.com/68705596/148697177-6e4436de-018a-47dc-8c75-160d753d2f55.png)

**Comment by JeS24** [comment]
Keep the console open and try downloading PDF. Then check for errors in the console, if the legend does not show up in the PDF.

**Comment by Shubhang-sharma** [comment]
![image](https://user-images.githubusercontent.com/68705596/148698208-e2b8effe-1834-4ff0-8ad6-c6f2852037ee.png)
(Using 100% scaling now)

**Comment by JeS24** [comment]
Pause Adblock or other javascript blocking extensions, if you have any. Then, hard reload the page (Ctrl+Shift+R) and try again. Also, can you try in another browser (Edge or Firefox)?

In my browsers (Edge Dev and Firefox), both the SDG website endpoint and the SDG server endpoint are working fine (with ad/script blockers enabled).

**Comment by Shubhang-sharma** [comment]
Yeah! Grammarly extension seems to be blocking things. Thanks :) It works
